#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore
picom
dunst &
$HOME/.config/polybar/launch.sh &

xinput set-prop "DLL0945:00 04F3:311C Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL0945:00 04F3:311C Touchpad" "libinput Tapping Enabled" 1

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a CoreShot state=floating
bspc rule -a discord desktop="^2" follow=on
