#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x polybar > /dev/null || polybar &

picom &
dunst &
flameshot &

feh --bg-scale $HOME/.config/feh/sakura.jpg

xinput set-prop "DLL0945:00 04F3:311C Touchpad" "libinput Click Method Enabled" 0 1
xinput set-prop "DLL0945:00 04F3:311C Touchpad" "libinput Tapping Enabled" 1

pgrep -x clipit > /dev/null || clipit &

blueman-applet &
nm-applet &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a CoreShot state=floating
bspc rule -a minecraft-launcher state=floating
bspc rule -a discord desktop="^2" follow=on
